language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN>
    - secure: "RLqCHVjTspeknERY/1D9F28aTVHgT7JiZphoqPmwYdqgAttQQJK2xHPtbCdU6U4HbjbZE/btu54aiBWWzQEZLrP/keqDooW5Bz1DIvjqQO9hvMePZ423g9z4V9Ccya/suWeIAYWFBrR6FzXEqoOovvR84F9YQTSckJ2FTPjBKGWJgjYHkviqZOKFOAtxVbnlysXFjy+4viORIj0jz5HNXX2DI5ajsJB6rBY+6yzeGrEAAndVxH77DD4PtSlujpSUPVWrW4Q7Ypbo9w/NiOw9djMm21beNEebHaAQ7Qjesu2X/Oo2bKlAGLSLz0ummhbJiyhD3tAodG19mo5TNac29lqcipGrXgD8cK10Nq7Uy262qdANupaCVmWTLabVw+cTUDyNktJi/ob/cKvJGtsFd4CdNk6m1S0lQnCOSIJ4hXSZ/NKT97auZ47aqSMYmzbZuzTz/DO3/+ctSNjFypxAtUsEm6a8ojwgUC4QJHFSIBeZDnZXjMl+fkj1VRD9JysXuR3mfDUTXL1maBCILJf4aQMtp8hYScrRoOR86bHB6KPFOf1yU2gr7PFGHd6e9Fz3xTz027oZMYQg+xsUTPJSyx/1a1AVWSNJOP4VktxtdI06eUYKwlAOvZyVABBBB0KAcrthrEzauf+wOetj//P1glY/BpUdShaY671WD9i+7Xw="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn lint
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-orange
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-orange
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod
